/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graphs;

public class App {


    public static void main(String[] args) {
        Person quicktest = new Person("derek");
        System.out.println(quicktest.getName());
        quicktest.setName("terry");
        System.out.println(quicktest.getName());

    }
}
