/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java.graphs;

import com.google.guava.graph;
import com.google.gson.Gson;

public class App {


    public static void main(String[] args) {


        MutableNetwork<Person, Person> relationship_network = NetworkBuilder.directed();

    }
}
